version: '3'

services:

  logstash:
    command: /usr/share/plugins/plugin/scripts/logstash-run.sh
    environment:
      - INTEGRATION=true
      - SECURE_INTEGRATION=${SECURE_INTEGRATION:-false}

  integration:
    build:
      context: ../../
      dockerfile: scripts/opendistro/Dockerfile.opendistro
      args:
        - INTEGRATION=true
        - SECURE_INTEGRATION=${SECURE_INTEGRATION:-false}
        - OPENDISTRO_VERSION=${OPENDISTRO_VERSION:-latest}
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ports:
      - "9200:9200"
    user: elasticsearch
