version: '3'

services:

  logstash:
    command: /usr/share/plugins/plugin/scripts/logstash-run.sh
    environment:
      - INTEGRATION=true


  integration:
    build:
      context: ../../
      dockerfile: scripts/opensearch/Dockerfile.opensearch
      args:
        - INTEGRATION=true
    command: /usr/share/opensearch/opensearch-run.sh
    ports:
      - "9200:9200"
    user: opensearch
