version: '3'

services:

  logstash:
    build:
      context: ../../
      dockerfile: scripts/Dockerfile
    command: /usr/share/plugins/plugin/scripts/unit-test/logstash-run.sh
    env_file: ../docker.env
    environment:
      - SPEC_OPTS
      - LOG_LEVEL # devutils (>= 2.0.4) reads the ENV and sets LS logging
      - CI=true
      - CI_ENV=$CI_ENV
    tty: true
    volumes:
      - shared:/shared
volumes:
  shared:
